USELESS_WORDS = ["<unk>"]
NORMALIZATION_RULES = {
    's': '',
    'es': '',
    'ed': '',
    'ing': '',
    'ies': 'y',
    'ied': 'y',
    'er': '',
    'est': '',
    'ful': '',
    'ment': '',
    'ness': '',
    'able': '',
    'ible': '',
    'al': '',
    'ial': '',
    'ical': '',
    'y': '',
    'ify': '',
    'ize': '',
    'ise': '',
    'ship': '',
    'ward': '',
    'wise': '',
}
